#!/usr/bin/env python3
from __future__ import annotations

import argparse
import json
import shutil
from collections import deque
from pathlib import Path
from PIL import Image, ImageFilter, ImageDraw


def is_bg_like(r: int, g: int, b: int, a: int) -> bool:
    if a < 10:
        return True
    mean = (r + g + b) / 3
    chroma = max(r, g, b) - min(r, g, b)

    # 밝은 회색/흰색 배경용. 무기 내부의 금색/주황은 보존되게 너무 넓게 잡지 않음.
    return mean > 145 and chroma < 42


def remove_border_background(img: Image.Image) -> Image.Image:
    img = img.convert("RGBA")
    w, h = img.size
    pix = img.load()

    visited = bytearray(w * h)
    bg = bytearray(w * h)
    q: deque[tuple[int, int]] = deque()

    def push(x: int, y: int) -> None:
        i = y * w + x
        if visited[i]:
            return
        visited[i] = 1
        r, g, b, a = pix[x, y]
        if is_bg_like(r, g, b, a):
            bg[i] = 1
            q.append((x, y))

    for x in range(w):
        push(x, 0)
        push(x, h - 1)
    for y in range(h):
        push(0, y)
        push(w - 1, y)

    while q:
        x, y = q.popleft()
        for nx, ny in ((x + 1, y), (x - 1, y), (x, y + 1), (x, y - 1)):
            if 0 <= nx < w and 0 <= ny < h:
                push(nx, ny)

    alpha = Image.new("L", (w, h), 255)
    alpha_px = alpha.load()

    for y in range(h):
        for x in range(w):
            if bg[y * w + x]:
                alpha_px[x, y] = 0

    alpha = alpha.filter(ImageFilter.GaussianBlur(0.5))
    out = img.copy()
    out.putalpha(alpha)

    bbox = out.getbbox()
    if bbox:
        out = out.crop(bbox)

    return out


def fit_square(img: Image.Image, size: int, pad_ratio: float = 0.07) -> Image.Image:
    img = img.convert("RGBA")
    max_w = int(size * (1 - pad_ratio * 2))
    max_h = int(size * (1 - pad_ratio * 2))

    scale = min(max_w / img.width, max_h / img.height)
    new_w = max(1, int(img.width * scale))
    new_h = max(1, int(img.height * scale))

    resized = img.resize((new_w, new_h), Image.Resampling.LANCZOS)
    canvas = Image.new("RGBA", (size, size), (0, 0, 0, 0))
    canvas.alpha_composite(resized, ((size - new_w) // 2, (size - new_h) // 2))
    return canvas


def make_preview(asset_id: str, display_name: str, texture: Image.Image, out_path: Path) -> None:
    canvas = Image.new("RGBA", (512, 512), (230, 230, 230, 255))
    draw = ImageDraw.Draw(canvas)

    # checker-ish center card
    draw.rounded_rectangle((64, 48, 448, 432), radius=24, fill=(245, 245, 245, 255), outline=(180, 180, 180, 255), width=2)

    big = texture.resize((320, 320), Image.Resampling.NEAREST)
    canvas.alpha_composite(big, (96, 72))

    draw.text((64, 448), display_name, fill=(20, 20, 20, 255))
    draw.text((64, 472), asset_id, fill=(70, 70, 70, 255))

    canvas.save(out_path)


def write_model_json(asset_id: str, out_path: Path) -> None:
    data = {
        "parent": "item/handheld",
        "textures": {
            "layer0": f"item/poro_weapons/{asset_id}"
        }
    }
    out_path.write_text(json.dumps(data, ensure_ascii=False, indent=2), encoding="utf-8")


def write_oraxen_yml(asset_id: str, display_name: str, material: str, out_path: Path) -> None:
    text = f'''# Generated by poro_weapon_factory
# 검수 후 실제 Oraxen items 폴더로 옮겨서 사용하세요.

{asset_id}:
  displayname: "{display_name}"
  material: {material}
  Pack:
    generate_model: true
    parent_model: "item/handheld"
    textures:
      - "poro_weapons/{asset_id}.png"
'''
    out_path.write_text(text, encoding="utf-8")


def write_itemsadder_yml(asset_id: str, display_name: str, material: str, out_path: Path) -> None:
    text = f'''# Generated by poro_weapon_factory
# 검수 후 실제 ItemsAdder contents 폴더 구조에 맞춰 옮겨서 사용하세요.

info:
  namespace: poro

items:
  {asset_id}:
    display_name: "{display_name}"
    resource:
      material: {material}
      generate: true
      textures:
        - "item/poro_weapons/{asset_id}.png"
'''
    out_path.write_text(text, encoding="utf-8")


def create_asset(args: argparse.Namespace) -> None:
    source = Path(args.source)
    if not source.exists():
        raise FileNotFoundError(f"source not found: {source}")

    asset_id = args.id
    display_name = args.display_name or asset_id
    material = args.material

    root = Path(args.out) / asset_id
    if root.exists() and args.force:
        shutil.rmtree(root)

    dirs = {
        "raw": root / "00_raw",
        "source": root / "01_source",
        "textures": root / "02_textures",
        "resourcepack": root / "03_resourcepack",
        "oraxen": root / "04_oraxen",
        "itemsadder": root / "05_itemsadder",
        "preview": root / "06_preview",
        "notes": root / "07_notes",
    }

    for d in dirs.values():
        d.mkdir(parents=True, exist_ok=True)

    raw_copy = dirs["raw"] / f"{asset_id}_raw{source.suffix.lower()}"
    shutil.copy2(source, raw_copy)

    img = Image.open(source).convert("RGBA")

    if args.no_bg_remove:
        cutout = img
    else:
        cutout = remove_border_background(img)

    cutout_path = dirs["source"] / f"{asset_id}_cutout.png"
    cutout.save(cutout_path)

    tex256 = fit_square(cutout, 256)
    tex128 = fit_square(cutout, 128)

    tex256_path = dirs["textures"] / f"{asset_id}_256.png"
    tex128_path = dirs["textures"] / f"{asset_id}_128.png"
    tex256.save(tex256_path)
    tex128.save(tex128_path)

    rp_tex_dir = dirs["resourcepack"] / "assets" / "minecraft" / "textures" / "item" / "poro_weapons"
    rp_model_dir = dirs["resourcepack"] / "assets" / "minecraft" / "models" / "item"
    rp_tex_dir.mkdir(parents=True, exist_ok=True)
    rp_model_dir.mkdir(parents=True, exist_ok=True)

    shutil.copy2(tex256_path, rp_tex_dir / f"{asset_id}.png")
    write_model_json(asset_id, rp_model_dir / f"{asset_id}.json")

    write_oraxen_yml(asset_id, display_name, material, dirs["oraxen"] / f"{asset_id}.yml")
    write_itemsadder_yml(asset_id, display_name, material, dirs["itemsadder"] / f"{asset_id}.yml")

    preview_path = dirs["preview"] / f"{asset_id}_preview.png"
    make_preview(asset_id, display_name, tex256, preview_path)

    manifest = {
        "asset_id": asset_id,
        "display_name": display_name,
        "material": material,
        "weapon_type": args.type,
        "source": str(source),
        "outputs": {
            "cutout": str(cutout_path),
            "texture_256": str(tex256_path),
            "texture_128": str(tex128_path),
            "preview": str(preview_path),
            "resourcepack_model": str(rp_model_dir / f"{asset_id}.json"),
            "oraxen_yml": str(dirs["oraxen"] / f"{asset_id}.yml"),
            "itemsadder_yml": str(dirs["itemsadder"] / f"{asset_id}.yml"),
        },
        "next_step": "Test as 2D handheld first. Promote to 2.5D only if the item reads well in inventory and hand view."
    }

    (root / "manifest.json").write_text(json.dumps(manifest, ensure_ascii=False, indent=2), encoding="utf-8")

    notes = f"""# {asset_id}

## 목적
이 결과물은 최종 2.5D 모델이 아니라, 먼저 인게임 2D handheld 검수를 하기 위한 양산용 출력입니다.

## 생성 파일
- 00_raw/{asset_id}_raw{source.suffix.lower()}
- 01_source/{asset_id}_cutout.png
- 02_textures/{asset_id}_256.png
- 02_textures/{asset_id}_128.png
- 03_resourcepack/assets/minecraft/textures/item/poro_weapons/{asset_id}.png
- 03_resourcepack/assets/minecraft/models/item/{asset_id}.json
- 04_oraxen/{asset_id}.yml
- 05_itemsadder/{asset_id}.yml
- 06_preview/{asset_id}_preview.png

## 검수 기준
1. 인벤토리에서 무기 실루엣이 읽히는가
2. 손에 들었을 때 너무 얇거나 작지 않은가
3. 색이 뭉개지지 않는가
4. 치장템으로 팔거나 보상으로 줄 만큼 매력이 있는가
5. 통과한 것만 2.5D 승격
"""
    (dirs["notes"] / "review_notes.md").write_text(notes, encoding="utf-8")

    print("")
    print("✅ poro weapon asset created")
    print(f"- root: {root}")
    print(f"- preview: {preview_path}")
    print(f"- texture: {tex256_path}")
    print(f"- oraxen: {dirs['oraxen'] / f'{asset_id}.yml'}")
    print(f"- itemsadder: {dirs['itemsadder'] / f'{asset_id}.yml'}")
    print("")
    print("next:")
    print(f"  explorer.exe {root}")


def main() -> None:
    parser = argparse.ArgumentParser(description="Poro weapon texture factory")
    sub = parser.add_subparsers(dest="cmd", required=True)

    p = sub.add_parser("create")
    p.add_argument("--id", required=True, help="asset id, e.g. flame_guardian_sword")
    p.add_argument("--type", default="greatsword", help="weapon type")
    p.add_argument("--source", required=True, help="source png")
    p.add_argument("--display-name", default=None)
    p.add_argument("--material", default="DIAMOND_SWORD")
    p.add_argument("--out", default="assets/source/items/weapons/_factory_output")
    p.add_argument("--no-bg-remove", action="store_true")
    p.add_argument("--force", action="store_true")
    p.set_defaults(func=create_asset)

    args = parser.parse_args()
    args.func(args)


if __name__ == "__main__":
    main()
